### ISSUE TITLE
issue with hibernate4-maven-plugin

### ISSUE THREAD

**Issue by ismail2015** [juplo/hibernate4-maven-plugin#6]
Hello,
I try to create a web project with AppFuse but when I execute the commande mvn jetty:run I get the following error:
[ERROR] Failed to execute goal de.juplo:hibernate4-maven-plugin:1.0.5:export (default) on project produit-app: No annotated classes found in directory C:\Users\Ismail Agoumi\produit-app\target\classes
 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.juplo:hibernate4-maven-plugin:1.0.5:export (default) on project produit-app: No annotated classes found in directory C
:\Users\Ismail Agoumi\produit-app\target\classes
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: No annotated classes found in directory C:\Users\Ismail Agoumi\produit-app\target\classes
        at de.juplo.plugins.hibernate4.Hbm2DdlMojo.execute(Hbm2DdlMojo.java:511)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

Development Environment:
MySQL Server 5.6
jdk1.8.0_45
apache-maven-3.3.3
AppFuse3.5.0

Could you give me some support to resolve this?

Thanks in advance

**Comment by juplo** [comment]
Hi,

this bug should be fixed in version 1.1.0



Am 16.06.2015 um 17:47 schrieb ismail2015:
> Hello,
> I try to create a web project with AppFuse but when I execute the
> commande mvn jetty:run I get the following error:
> [ERROR] Failed to execute goal
> de.juplo:hibernate4-maven-plugin:1.0.5:export (default) on project
> produit-app: No annotated classes found in directory C:\Users\Ismail
> Agoumi\produit-app\target\classes
> -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to
> execute goal de.juplo:hibernate4-maven-plugin:1.0.5:export (default) on
> project produit-app: No annotated classes found in directory C
> :\Users\Ismail Agoumi\produit-app\target\classes
> at
> org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
> at
> org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> at
> org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> at
> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> at
> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> at
> org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> at
> org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
> at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
> at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.MojoFailureException: No annotated
> classes found in directory C:\Users\Ismail Agoumi\produit-app\target\classes
> at de.juplo.plugins.hibernate4.Hbm2DdlMojo.execute(Hbm2DdlMojo.java:511)
> at
> org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> at
> org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
> ... 20 more
> [ERROR]
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> 
> Development Environment:
> MySQL Server 5.6
> jdk1.8.0_45
> apache-maven-3.3.3
> AppFuse3.5.0
> 
> Could you give me some support to resolve this?
> 
> Thanks in advance
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juplo/hibernate4-maven-plugin/issues/6>.
> 

-- 
juplo
Inhaber: Kai Moritz

Tel: +49 (0)176 20 50 47 47
kai@juplo.de
http://juplo.de
